include $(HEADER)

CPP_FLAGS += -I$(CONTRIB_DIR)/live555/BasicUsageEnvironment/include -I$(CONTRIB_DIR)/live555/UsageEnvironment/include -I$(CONTRIB_DIR)/live555/groupsock/include -I$(CONTRIB_DIR)/live555/liveMedia/include
TARGET = libaccess.a

include $(STATIC_LIB)
