include $(HEADER)

CPP_FLAGS += -I$(CONTRIB_DIR)/freetype/include -I$(CONTRIB_DIR)/fribidi/lib -I$(CONTRIB_DIR)/fribidi/charset -I$(CONTRIB_DIR)/fontconfig
TARGET = libtextrenderer.a

include $(STATIC_LIB)
